"""
Django settings for pkms project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '**************************************************'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.18.78.61', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS=['http://localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'markup',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pkms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pkms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'public/static'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'public/media'

# 静态html，分系统和独立页，其中系统又分私有和公开的，公开的和独立页可放一起，nginx之类可直接访问
# PRIVATE_HTML_ROOT 为系统私有， PUBLIC_HTML_ROOT 公开的, PUBLIC_STATIC_HTML_ROOT 系统公开的

# rst转为静态html，公开的，允许访客查看的，配合nginx就对应该目录下
PUBLIC_HTML_URL = '/public_html/'  # 若自己无权限配制 server alias 只能和PUBLIC_HTML_ROOT配制的目录名一样

# rst转为静态html目录，nginx可配制拒绝访问，或设置在ngixn访问不到的目录
PRIVATE_HTML_ROOT = BASE_DIR / 'static_html'
# public 静态html路径
PUBLIC_HTML_ROOT = BASE_DIR / 'public/public_html'
PUBLIC_STATIC_HTML_ROOT = BASE_DIR / 'public/static_html'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


############### 系统静态化html 设计 ################
# 目录树上a标签添加 href 属性，未发布的附值'#', 发布的指向静态化html ，便于搜索引擎收录
# 静态化文件名： 数据库id加盐的取md5值，前16位系统私有html文件名，8:24位则是公开的html文件名
# 以年(2024)为分目录，避免重名
# 将私密节点静态化保存在 PRIVATE_HTML_ROOT 下， 由django直接读取返回，避免每次都需要源码编译
# 发布的节点，系统内嵌页存放在PUBLIC_STATIC_HTML_ROOT，单页内容存放在 PUBLIC_HTML_ROOT
# 项目启动时，检查这些目录，若不存在就创建

STATIC_ROOT.mkdir(parents=True, exist_ok=True)
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
PRIVATE_HTML_ROOT.mkdir(parents=True, exist_ok=True)
PUBLIC_HTML_ROOT.mkdir(parents=True, exist_ok=True)
PUBLIC_STATIC_HTML_ROOT.mkdir(parents=True, exist_ok=True)

LOGOUT_REDIRECT_URL = '/'
